#MCAdmin Mod Configuration
#Tue Apr 14 12:07:15 CST 2026
security.allowed_commands=list,say,op,deop,kick,ban,pardon,whitelist,save-all,time,weather,gamemode,tp,give,tell,msg,effect,difficulty,gamerule,seed,title,tellraw,stop
security.dangerous_commands=ban,op,deop,stop,whitelist
security.require_confirmation=false
server.id=mc_6a81106d
server.restart_script=
status.report_interval=5000
ws.token=BeHvYrsaAoJ0oi5W8QyrwpZI_i3t7b6A
ws.url=ws\://47.113.221.26/mc-admin/ws/mod
